<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0wzJdLP' shared service.

return $this->privates['.service_locator.0wzJdLP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PageController::new' => ['privates', '.service_locator.JESRXF2', 'get_ServiceLocator_JESRXF2Service.php', true],
    'App\\Controller\\PageController:new' => ['privates', '.service_locator.JESRXF2', 'get_ServiceLocator_JESRXF2Service.php', true],
], [
    'App\\Controller\\PageController::new' => '?',
    'App\\Controller\\PageController:new' => '?',
]);
