<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wKYfSH2' shared service.

return $this->privates['.service_locator.wKYfSH2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PageController::Service' => ['privates', '.service_locator.v9qO.vD', 'get_ServiceLocator_V9qO_VDService.php', true],
    'App\\Controller\\PageController::new' => ['privates', '.service_locator.JESRXF2', 'get_ServiceLocator_JESRXF2Service.php', true],
    'App\\Controller\\PageController:Service' => ['privates', '.service_locator.v9qO.vD', 'get_ServiceLocator_V9qO_VDService.php', true],
    'App\\Controller\\PageController:new' => ['privates', '.service_locator.JESRXF2', 'get_ServiceLocator_JESRXF2Service.php', true],
], [
    'App\\Controller\\PageController::Service' => '?',
    'App\\Controller\\PageController::new' => '?',
    'App\\Controller\\PageController:Service' => '?',
    'App\\Controller\\PageController:new' => '?',
]);
